### ISSUE TITLE
Geoportal + GBL Admin - Todo List

### ISSUE THREAD

**Issue by ewlarson** [geobtaa/geoportal#535]
- [x] File uploads not working (can select a file, but upload step fails (`Failed to load resource: the server responded with a status of 500`)
- [x] Solr indexing is slowwwwwww
- [x] Add user not working
- [ ] JS: Cannot read properties of undefined (reading 'placeMarkers')
- [ ] "Contact Support" link defaults to current page. It could be geoportal@btaa.org
- [x] Multiple downloads are not showing up: https://geodev.btaa.org/catalog/0455d309-e4e9-473e-8c3f-b42a6a2e16fc
- [x] Missing SVGs (admin views / title spacing bug)
- [x] Sidecar Image Harvesting is broken --  ERROR:  relation "sidecar_image_transitions" does not exist
- [x] Configure Nginx for WebSockets (already done in dev and prod)
- [x] Cannot seem to manually create and save a record - "Document was successfully created." - nothing there? 
- [x] Blazer not working
- [x] Admin > Run Import > Error - Traject::SolrJsonWriter - neither solr.update_url and solr.url set
- [x] New Document 500s
- [x] Admin > Import CSV file > 500s (permissions error)
- [x] Click user email address
- [ ] BrowseEverything (Samvera's Cloud storage UI)

**Comment by karenmajewicz** [comment]
Lower priority fixes

- [ ] Move "GeoBlacklight Home" link to right/end of menu list. (I keep clicking on it by habit when I only occasionally want to go to the homepage from the admin page.

**Comment by ewlarson** [comment]
@mberkowski / I'm seeing geodev's geoportal production.log file fill up with "Failed to upgrade to WebSocket" lines. Do we need to reconfigure that puma instance to support ActionCable websockets?

I have a vague memory of something being tweaked for GEOMG...

**Comment by mberkowski** [comment]
Yes, nginx probably needs to be touched up.

**Comment by ewlarson** [comment]
@karenmajewicz // Re: multiple downloads not showing up. I just reindexed Solr and the downloads are there. Not sure why they didn't appear immediately after you added them, but the document indexer does the right thing here.
