### ISSUE TITLE
Footer - Review and redesign

### ISSUE THREAD

**Issue by ewlarson** [geobtaa/geoportal#557]
The application footer has not been reviewed for a few years now.

Pages to address
* Harmful language statement 
* Privacy policy
* Accessibility statement

Also, do we still need the UMN IT footer?

**Comment by ewlarson** [comment]
```[tasklist]
### Tasks
- [ ] Move Feedback to Top
- [ ] Remove extra "white" margin above UMN footer
- [ ] Remove Help us button
```
